### ISSUE TITLE
Robot Hands Unexpected Behavior :(

### ISSUE THREAD

**Issue by raybrshen** [raybrshen/robot_sds#4]
Guess it's caused by low voltage or current of power supply.
Running ROS serial node, connection to device sometimes works most of the times doesn't.

**Comment by cindywang** [comment]
Go PUMPKIN GO!!! :)

**Comment by raybrshen** [comment]
Issue Update
- In the embedded C code, after mask out two of the servos, robot hand works fine.
- All servos are connected in parallel, so the voltage of each servo is the same, but the current of the circuit will adds up.

So from here, we can see two potential causes:
- the memory space required for code of five servos is too much for the Arduino micro-controller
- the total current of five servos is too high for the circuit and gives out unexpected signals

I feel the second make more sense though, at least we know what to test next.
